name: hisabi
description: تطبيق محاسبي شخصي (حسابي) لتتبع الدخل والمصروفات والأصول والخصوم.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  fl_chart: ^0.66.2
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^8.0.0
  image_picker: ^1.0.7
  flutter_local_notifications: ^16.2.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700