name: Flutter Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # جافا 17 ضرورية لـ AGP 8+
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      # آخر قناة مستقرة من Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # إصلاح هيكل المشروع وملفات Gradle داخل نفس المجلد
      - run: flutter create .

      - run: flutter pub get
      - run: flutter build apk --release

      - name: رفع ملف APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk