name: Flutter Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      # إنشاء هيكل مشروع جديد ثم نسخ ملفاتك فوقه
      - run: |
          flutter create temp_app
          cp -r lib temp_app/
          cp pubspec.yaml temp_app/
          cp -r assets temp_app/ || true
          mv temp_app/* .
          mv temp_app/.* . || true

      - run: flutter pub get
      - run: flutter build apk --release

      - name: رفع ملف APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
